# -*- coding: utf-8 -*-
"""question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cxtTdqAipQxClLJKuxQNMWt_IZBeDQEU

##Question 1

Step 1
"""

import pandas as pd

"""Step 2 and 3"""

# step 2 and 3
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user" , delimiter='|')

print(users.head())

"""Step 4"""

mean_age_per_occupation = users.groupby('occupation')['age'].mean().reset_index()
mean_age_per_occupation = mean_age_per_occupation.rename(columns={'age': 'mean_age'})
print("Mean age per occupation:")
print(mean_age_per_occupation)

"""Step 5"""

users_male = users[users['gender'] == "M"]
# print(users_male)
male_ratio_per_occupation = users_male.groupby("occupation").size() / users.groupby("occupation").size()
# sorting in descending ratio
male_ratio_per_occupation.sort_values(ascending = False, inplace = True)
print("Male ratio per occupation (sorted descending):")
print(male_ratio_per_occupation)

"""Step 6"""

min_user_age_per_occupation = users.groupby("occupation")['age'].agg(min_age = "min" , max_age = "max")
print("For each occupation, the minimum and maximum ages:")
print(min_user_age_per_occupation)

"""Step 7"""

mean_age_per_occupation_and_sex = users.groupby(['occupation', 'gender'])['age'].agg(mean_age = 'mean')
print("For each combination of occupation and sex, the mean age:")
print(mean_age_per_occupation_and_sex)

"""Step 8"""

percentage_of_occupation_gender_wise = (users.groupby(["occupation" , "gender"]).size() / users.groupby("occupation").size())*100
print("For each occupation the percentage of women and men:")
print(percentage_of_occupation_gender_wise)

